### ISSUE TITLE
Please create dunfell branch

### ISSUE THREAD

**Issue by pbrkr** [EmbeddedAndroid/meta-rtlwifi#16]
As there is no dunfell branch in this repo, the OE layer index does not show meta-rtlwifi when you search for layers compatible with the dunfell release. We know that the master branch of meta-rtlwifi is compatible with several recent releases but it looks like the OE layer index only looks at branch names.

This breaks the listing for meta-sancloud in the layer index as our layer depends on meta-rtlwifi. The dunfell branch of meta-sancloud is rejected as the layer index thinks the dependencies cannot be met (as meta-rtlwifi has no corresponding dunfell branch).

This should be easily fixed by creating a dunfell branch in this repo.

**Comment by EmbeddedAndroid** [comment]
Thanks for the report. I've pushed dunfell branch out now.
