### ISSUE TITLE
Old branch names in LAYERSERIES_COMPAT

### ISSUE THREAD

**Issue by pbrkr** [EmbeddedAndroid/meta-rtlwifi#19]
Is this layer tested with all the old branch names in LAYERSERIES_COMPAT? I worry seeing so many old branches named that support for some of them may have bitrotted if it's not been tested with changes to this layer.

**Comment by ricardosalveti** [comment]
+1, I believe it might be better to drop the old ones (e.g. rocko sumo thud warrior).

**Comment by EmbeddedAndroid** [comment]
Fixed in **https://github.com/EmbeddedAndroid/meta-rtlwifi/commit/b8327c556e9f03708bb8ef6d1678e520cecc98e7**
